name:                SVGtoTEX
version:             0.1.0.0
github:              "SlimTim10/SVGtoTEX"
license:             BSD3
author:              "SlimTim10"
maintainer:          "slimtim10@gmail.com"
copyright:           "SlimTim10"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/SlimTim10/SVGtoTEX#readme>

dependencies:
- base >= 4.7 && < 5
- process >= 1.6.3.0
- directory >= 1.3.2.2
- pdfinfo >= 1.5.4
- text >= 1.2.3.0

library:
  source-dirs: src

executables:
  svg_to_tex:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SVGtoTEX

tests:
  SVGtoTEX-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SVGtoTEX
